name: Node CI

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: git config --get remote.origin.url
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ GH_TOKEN }}
        env:
          GH_TOKEN: ${{secrets.npm_token}}


