name: Deploy to GH-Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: yarn deploy:storybook
